# Generated by Django 4.1 on 2024-09-29 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ("title",)},
        ),
    ]
